### ISSUE TITLE
GitHub token is required

### ISSUE THREAD

**Issue by thomasbnt** [antfu/sponsorkit#13]
What I have as files : 
- `./workflows/sponsor_gen.yml`
- `./package.json` (like [this one](https://github.com/antfu/sponsorkit/blob/main/example/package.json))
- `./sponsor.config.ts` with defaults configs.

In settings, I've got **SPONSORS_TOKEN** in Actions secrets with _org:read_ and _user:read_ perms.

When I run the action, I've got this error : 

```bash
Run npm run build
  npm run build
  shell: /usr/bin/bash -e {0}
  env:
    SPONSORKIT_GITHUB_TOKEN: ***
    SPONSORKIT_GITHUB_LOGIN: thomasbnt

> build
> sponsorkit

[log] 
SponsorKit v0.[2](https://github.com/thomasbnt/sponsors/runs/5741141885?check_suite_focus=true#step:5:2).2

[info] Fetching sponsorships from github...
Error: GitHub token is required
    at fetchGitHubSponsors (/home/runner/work/sponsors/sponsors/node_modules/.pnpm/sponsorkit@0.2.2/node_modules/sponsorkit/dist/chunks/index.cjs:284:11)
    at Object.fetchSponsors (/home/runner/work/sponsors/sponsors/node_modules/.pnpm/sponsorkit@0.2.2/node_modules/sponsorkit/dist/chunks/index.cjs:279:12)
    at run (/home/runner/work/sponsors/sponsors/node_modules/.pnpm/sponsorkit@0.2.2/node_modules/sponsorkit/dist/cli.cjs:[3](https://github.com/thomasbnt/sponsors/runs/5741141885?check_suite_focus=true#step:5:3)[9](https://github.com/thomasbnt/sponsors/runs/5741141885?check_suite_focus=true#step:5:9):32)
    at async Object.handler (/home/runner/work/sponsors/sponsors/node_modules/.pnpm/sponsorkit@0.2.2/node_modules/sponsorkit/dist/cli.cjs:[13](https://github.com/thomasbnt/sponsors/runs/5741141885?check_suite_focus=true#step:5:13)0:3)
Error: Process completed with exit code 1.
```

How I can resolve this error?

**Comment by thomasbnt** [comment]
It works! Thanks for your amazing work @antfu ! 🚀
